#!/bin/bash

# Hostel Mess Management System - Quick Start Commands
# =====================================================

echo "🚀 Hostel Mess Management System - Quick Start"
echo "=============================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Prerequisites Check${NC}"
echo "- Node.js v16+: $(node --version 2>/dev/null || echo 'NOT INSTALLED')"
echo "- npm: $(npm --version 2>/dev/null || echo 'NOT INSTALLED')"
echo "- Flutter: $(flutter --version | head -1 2>/dev/null || echo 'NOT INSTALLED')"
echo "- MySQL: Please ensure MySQL is running on localhost:3306"
echo ""

echo -e "${YELLOW}⚙️  BACKEND SETUP${NC}"
echo "=================================="
echo ""
echo "cd backend"
echo ""
echo "# 1. Install dependencies"
echo "npm install"
echo ""
echo "# 2. Create/Update .env file with your configuration:"
echo "#    CP backend/.env.example → backend/.env"
echo "#    Edit DATABASE_URL, JWT_SECRET, ADMIN_PASSWORD, etc."
echo ""
echo "# 3. Setup database"
echo "npm run prisma:push      # Push schema to database"
echo "npm run seed             # Seed admin user and settings"
echo ""
echo "# 4. Start development server"
echo "npm run dev              # Runs on http://localhost:5000"
echo ""

echo -e "${YELLOW}⚙️  FRONTEND SETUP${NC}"
echo "============================="
echo ""
echo "cd mess_app_frontend"
echo ""
echo "# 1. Get Flutter dependencies"
echo "flutter pub get"
echo ""
echo "# 2. (OPTIONAL) Update API base URL in lib/config/app_environment.dart"
echo "#    - Android Emulator: http://10.0.2.2:5000/api   ✅ DEFAULT"
echo "#    - iOS Simulator: http://127.0.0.1:5000/api"
echo "#    - Physical Device: http://<YOUR-IP>:5000/api"
echo ""
echo "# 3. Run the app"
echo "flutter run               # Choose device when prompted"
echo ""

echo -e "${GREEN}✅ EXPECTED OUTPUT${NC}"
echo "==================="
echo ""
echo "Backend:"
echo "  ✅ Firebase initialized successfully"
echo "  ✅ Database connected successfully"
echo "  Server running on port 5000"
echo ""
echo "Frontend:"
echo "  ✅ Firebase initialized successfully"
echo "  ✅ FCM initialized successfully"
echo "  App shows login screen"
echo ""

echo -e "${YELLOW}🧪 QUICK TEST${NC}"
echo "==============="
echo ""
echo "1. Backend health check:"
echo "   curl http://localhost:5000/api/auth/login"
echo "   (Should give 404 error - that's OK, means backend is up)"
echo ""
echo "2. In the app:"
echo "   - Go to Sign Up"
echo "   - Enter test credentials (role=ADMIN is default)"
echo "   - Submit"
echo "   - Check email for verification (or use debug endpoint in dev)"
echo "   - Go to login"
echo "   - Login with same credentials"
echo "   - ✅ Should see dashboard"
echo ""

echo -e "${GREEN}📝 IMPORTANT NOTES${NC}"
echo "==================="
echo ""
echo "✅ All bugs are fixed - you can run the app now!"
echo ""
echo "🔐 Environment Variables (.env):"
echo "   - DATABASE_URL: Update with your MySQL connection"
echo "   - JWT_SECRET: Change from default in production"
echo "   - ADMIN_PASSWORD: Set a strong password"
echo "   - SMTP: Configure if you need email verification"
echo ""
echo "📧 Email Verification:"
echo "   - For development: Use backend debug endpoint"
echo "   - For production: Configure SMTP in .env"
echo ""
echo "🔑 Token Management:"
echo "   - Tokens are automatically attached to all API requests"
echo "   - DioClient handles token storage and retrieval"
echo "   - No manual token management needed"
echo ""
echo "📱 Multi-Platform:"
echo "   flutter run -d android    # Run on Android device/emulator"
echo "   flutter run -d ios        # Run on iOS device/simulator"
echo "   flutter run -d chrome     # Run on web (Chrome)"
echo "   flutter run -d windows    # Run on Windows"
echo "   flutter run -d linux      # Run on Linux"
echo ""

echo -e "${BLUE}🎯 All Bugs Fixed!${NC}"
echo ""
echo "The application is now clean and ready to run."
echo "Follow the steps above to get started."
echo ""
