ALTER TABLE `User`
  ADD COLUMN IF NOT EXISTS `passwordResetTokenHash` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `passwordResetExpiresAt` DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS `passwordResetUsedAt` DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS `emailVerificationTokenHash` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `emailVerificationExpiresAt` DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS `emailVerifiedAt` DATETIME(3) NULL;
